// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_AflGhQGR5Yi8nkG5Iw2x-V8wRJuV1go',
    appId: '1:870492601825:web:a631118ff86616b5f9e6a0',
    messagingSenderId: '870492601825',
    projectId: 'askh-english-app',
    authDomain: 'askh-english-app.firebaseapp.com',
    storageBucket: 'askh-english-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGLreJnEzTgqclZKVjDBBR7wDcJMPhuBo',
    appId: '1:870492601825:android:da3fb6ff73226331f9e6a0',
    messagingSenderId: '870492601825',
    projectId: 'askh-english-app',
    storageBucket: 'askh-english-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7623zZRdJYAmYqwJYSLxyECKcaqoQl94',
    appId: '1:870492601825:ios:377fbac1ccee76dcf9e6a0',
    messagingSenderId: '870492601825',
    projectId: 'askh-english-app',
    storageBucket: 'askh-english-app.firebasestorage.app',
    iosBundleId: 'com.example.akshEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7623zZRdJYAmYqwJYSLxyECKcaqoQl94',
    appId: '1:870492601825:ios:377fbac1ccee76dcf9e6a0',
    messagingSenderId: '870492601825',
    projectId: 'askh-english-app',
    storageBucket: 'askh-english-app.firebasestorage.app',
    iosBundleId: 'com.example.akshEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_AflGhQGR5Yi8nkG5Iw2x-V8wRJuV1go',
    appId: '1:870492601825:web:556ec523f16ec15df9e6a0',
    messagingSenderId: '870492601825',
    projectId: 'askh-english-app',
    authDomain: 'askh-english-app.firebaseapp.com',
    storageBucket: 'askh-english-app.firebasestorage.app',
  );

}